[DOCS] Added contributing section to the documentation
k0sproject/k0smotron pull request #484
Opened 2024-03-06 09:04 UTC by MagdaDziadosz

Added contributing section to the documentation:

- [ ] Overview 
    - [ ] Tracking issues - included in overview
-  [ ] Workflow
    - [ ] Fork the project
    - [ ] Commit and push the change
    - [ ] Open a pull request
- [ ] Coding guidelines - waiting for dev input
- [ ] Testing
    - [ ] Contributing to documentation - included in workflow and testing

2024-03-06 09:51 UTC, makhov commented on docs/contributing/contribute-testing.md
> +   Note that the last test may produce a false failing result, so it might fail on
This paragraph is redundant for k0smotron

2024-03-06 09:53 UTC, makhov commented on docs/contributing/contribute-testing.md
> +### Conformance testing
This section is also redundant

2024-03-06 13:20 UTC, KoryKessel-Mirantis commented on README.md
> +Contributions to k0smotron are welcome! Read the [Contribution Guidelines](docs/contributing/contribute-overview.md) to learn how you can participate in enhancing this tool.
I suggest flipping the clauses in the second sentence to read:

To learn how you can contribute to the growth and enhancement of k0smotron, please read our [Contribution Guidelines](docs/contributing/contribute-overview.md).

2024-03-06 13:55 UTC, makhov approved these changes

2024-03-06 15:16 UTC, KoryKessel-Mirantis requested changes

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-testing.md
> +It cleans up all the intermediate files and directories created during the k0smotron build.
Suggest:  To clean up the local workspace, run `make clean'. This removes all the intermediate files and directories that were created during the k0smotron build.

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +by creating pull requests.
Create pull requests to...

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +2. On the top, right-hand side, click "Fork" and select your username for the fork destination.
Suggest "In the top right-hand corner, "

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +1. Create a feature branch and switch to it:
Suggest: "Create and switch to a..."

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +If you need to add some additional changes or tests use `commit --amend` command.
Suggest: "To add..."

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +When everything is ready, push your changes to your fork's repository:
Suggest: Push your changes to the fork repository.

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +Follow GitHub's documentation on how to [create a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests
Suggest: "Refer to the official GitHub documentation [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +The k0smotron team will review your pull request.
Suggest: after 'pull request' insert 'and leave comments.'

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +Keep the PRs small if possible to speed up the review process.
Need commas.

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +and so on.
Separate 'Squash' sentence out to a new paragraph and attach the sentence following to it.

2024-03-06 15:16 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-workflow.md
> +You can run multiple iteration of `rebase`/`push -f`, if needed.
If necessary, for whatever reason...

2024-03-06 22:20 UTC, juanluisvaladas commented
LGTM both as is or with the suggestions work for me as well.
Needs rebase, feel free to ping me on slack for stamping it.

2024-03-13 14:33 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-overview.md
> +by [opening a GitHub issue in a k0smotron project](https://github.com/k0sproject/k0smotron/issues).
LGTM

2024-03-13 14:34 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-overview.md
> +# Contributing to k0smotron
LGTM

2024-03-13 14:34 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-overview.md
> +We are looking forward to working with you to make k0smotron better.
LGTM

2024-03-13 14:34 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-overview.md
> +The following document is a set of helpful guidelines and instructions for the contributors.
LGTM

2024-03-13 14:35 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-overview.md
> +To stay updated, you can subscribe to an issue to receive notifications about the latest comments.
LGTM

2024-03-13 14:51 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-overview.md
> +By contributing, you agree that your contributions will be licensed as followed:
'followed' should be 'follows'

2024-03-13 15:45 UTC, KoryKessel-Mirantis requested changes

2024-03-13 15:45 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-testing.md
> +4. Pull request is rebased against upstream main branch.
I suggest rethinking this edit.

First, can a PR be merged if any of these conditions are not fulfilled? The 'should' raises questions where perhaps questions should not be raised.

Second, if it is not a 'should' but is indeed a 'must', then the conditions should be presented in the past tense, as they were prior to this edit.

If the conditions are a 'must', I suggest:

For a pull request to be merged, all of the following must be true:

1. The PR has passed all of the automated tests (style, build and conformance tests).
2. All of the PR commits have been signed with the `--signoff` option.
3. The PR has been reviewed and approved by a code owner.
4. The PR has been rebased against upstream main branch.

2024-03-13 15:45 UTC, KoryKessel-Mirantis commented on docs/contributing/contribute-testing.md
> +This removes all the intermediate files and directories created during the k0smotron build.
Suggest:

Run 'make clean' to remove all the intermediate files and directories created locally during the k0smotron build.

2024-03-14 08:11 UTC, MagdaDziadosz commented
@juanluisvaladas ready for final check

2024-03-14 13:01 UTC, KoryKessel-Mirantis approved these changes

2024-03-14 15:03 UTC, merged