[DOCS] Added update procedure
k0sproject/k0smotron pull request #488
Opened 2024-03-06 16:07 UTC by MagdaDziadosz

Added upgrade procedure for standalone cluster and Cluster API

2024-03-06 16:42 UTC, makhov approved these changes

2024-03-11 11:17 UTC, ogusarenko commented on docs/update/update-cluster-pod.md
> +4. Run the `kubectl apply -f ./path-to-file.yaml` command to update the resources.
4. Update the resources:

   ```bash
   kubectl apply -f ./<path-to-config-file>.yaml
   ```

2024-03-11 11:20 UTC, ogusarenko commented on docs/update/update-cluster-pod.md
> +2. Change all the k0s versions to the latest one:
That would be nice to add a link to the k0s describing the versioning. And/or add the command there to find out what the latest k0s version is, if it exists.

2024-03-11 12:24 UTC, MagdaDziadosz commented on docs/update/update-cluster-pod.md
> +    To prevent data loss, you can update workers manually or use [k0s autopilot](https://docs.k0sproject.io/stable/autopilot/) instead.
That is a great question for @makhov

2024-03-14 10:25 UTC, jnummelin requested changes

2024-03-14 10:25 UTC, jnummelin commented on docs/update/update-cluster-pod.md
> +   Do not configure persistence in production environment.
I think this is supposed to read like "do not configure `hostPath` persistence in production..."

2024-03-14 10:25 UTC, jnummelin commented on docs/update/update-cluster-pod.md
> +
This seems to be missing the closing code segment

2024-03-14 10:25 UTC, jnummelin commented on docs/update/update-standalone.md
> +   Do not configure persistence in production environment.
Again, probably meant hostPath here

2024-03-15 09:30 UTC, jnummelin approved these changes

2024-03-25 15:11 UTC, ogusarenko reviewed
Please apply my comments from the 1st file to the 2nd file as well. Thank you!

2024-03-25 15:11 UTC, ogusarenko commented on docs/update/update-cluster-pod.md
> +the k0s version and machine names in the YAML configuration file.
```suggestion
the k0s version and machine names in the YAML configuration file:
```

2024-03-25 15:11 UTC, ogusarenko commented on docs/update/update-cluster-pod.md
> +   Do not configure `hostPath` persistence in production environment.
Using the `hostPath` volume type introduces many security risks. Avoid configuring persistence for volumes of the `hostPath` type.

2024-03-25 15:11 UTC, ogusarenko commented on docs/update/update-cluster-pod.md
> +   Learn more from the official Kubernetes documentation on [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath).
```suggestion
   Learn more from [official Kubernetes documentation: hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath).
```

2024-03-25 15:11 UTC, ogusarenko commented on docs/update/update-cluster-pod.md
> +3. Change all the k0s versions to [the target one](https://docs.k0sproject.io/v1.29.2+k0s.0/releases/#k0s-release-and-support-model). For example:
Remove this link from the step, not the distract the reader. You can add a see also block at the end including the ref

2024-03-25 15:11 UTC, ogusarenko commented on docs/update/update-cluster-pod.md
> +   ```
That would be great to have a summary at the end with the verification step

2024-03-28 12:46 UTC, ogusarenko approved these changes

2024-03-28 12:46 UTC, ogusarenko commented on docs/update/update-standalone.md
> +The update procedure is completed, you now have the latest k0smotron version.
```suggestion
The update procedure is completed, you now have the target version of k0smotron.
```

2024-04-03 13:47 UTC, merged