Controlplane scaling
k0sproject/k0smotron pull request #493
Opened 2024-03-12 13:21 UTC by makhov

2024-03-18 09:02 UTC, juanluisvaladas approved these changes
Just a few comments on things that I think can be improved but not worth blocking the merge

2024-03-18 09:02 UTC, juanluisvaladas commented on internal/controller/controlplane/util.go
> +		return nil, err // TODO
```suggestion
		return nil, fmt.Errorf("Error generating %s clientconfig: %w", cluster.Name, err)
```

So that we can debug a bit better.

2024-03-18 09:02 UTC, juanluisvaladas commented on internal/controller/controlplane/util.go
> +		return nil, err // TODO
```suggestion
		return nil, fmt.Errorf("Error generating %s restconfig:  %w", cluster.Name, err)
```

2024-03-18 10:42 UTC, jnummelin requested changes

2024-03-18 10:55 UTC, makhov commented on docs/update/update-capi-cluster.md
> +1. Localize the configuration of deployed k0smotron cluster in your repository. For example:
Done

2024-03-18 10:55 UTC, makhov commented on docs/update/update-capi-cluster.md
> +2. Change all the k0s versions to [the target one](https://docs.k0sproject.io/v1.29.2+k0s.0/releases/#k0s-release-and-support-model). For example:
Done

2024-03-18 10:56 UTC, makhov commented on internal/controller/bootstrap/controlplane_bootstrap_controller.go
> +	commands = append(commands, "(command -v systemctl > /dev/null 2>&1 && systemctl daemon-reload && systemctl enable k0sleave.service && systemctl start k0sleave.service || true)")
Done

2024-03-18 10:56 UTC, makhov commented on internal/controller/controlplane/helper.go
> +						"linux-arm64": {
Done

2024-03-18 10:56 UTC, makhov commented on internal/controller/controlplane/util.go
> +		return nil, err // TODO
Done

2024-03-18 10:56 UTC, makhov commented on internal/controller/controlplane/util.go
> +		return nil, err // TODO
Done

2024-03-18 10:56 UTC, makhov commented on internal/controller/controlplane/util.go
> +		return nil, err // TODO
Done

2024-03-18 10:56 UTC, makhov commented on docs/update/update-capi-cluster.md
> +the control plane deployment.
Done

2024-03-18 10:57 UTC, makhov commented on docs/update/update-capi-cluster.md
> +  change the `version` field in the JSON from `Cordoning` to `ApplyingUpdate`.
Thanks, it's `status` field. Fixed

2024-03-18 10:57 UTC, makhov commented on docs/update/update-capi-cluster.md
> +k0smotron does not deploy new machines for the new nodes
Done

2024-03-18 10:57 UTC, makhov commented on docs/update/update-capi-cluster.md
> +
Done

2024-03-18 12:07 UTC, juanluisvaladas approved these changes
LGTM

2024-03-19 07:39 UTC, jnummelin approved these changes

2024-03-19 10:32 UTC, merged