Add controlplane upgrade e2e test using capi framework
k0sproject/k0smotron pull request #845
Opened 2024-12-04 17:59 UTC by apedriza

fix #775 

This PR makes use of the [e2e framework](https://pkg.go.dev/sigs.k8s.io/cluster-api/test/framework) built by CAPI and used by several providers. This is intended to address current problems described in this [issue](https://github.com/k0sproject/k0smotron/issues/775) such as code repetition or a proper collection of logs in case of failure. Also, this approach prepares the ground for testing using an agnostic infrastructure provider. By adopting this framework, much of the code required for each test (such as bootstrap management cluster setup) is imported from the CAPI framework. On the other hand, a log dump of all relevant test components logs + configuration used is implemented if the test fails, improving the debugging capability of the test in case of failure. 

For now, a basic configuration is sufficient. The intention is to migrate the current CAPI smoke tests little by little from the current approach to the proposed one.

2024-12-18 11:55 UTC, makhov commented
I'm personally not a big fan of Ginkgo (if not to say more), could we use the framework without it?

2025-02-04 13:26 UTC, jnummelin requested changes
Added couple questions to clarify things

Couple of small fixes IMO needed, looks pretty good in general

2025-02-04 13:26 UTC, jnummelin commented on .github/workflows/go.yml
> +    name: E2E migration (WIP)
WIP still?

2025-02-04 13:26 UTC, jnummelin commented on e2e/util/cleanup.go
> +	clusgerNamespace := input.Cluster.GetNamespace()
```suggestion
	clusterNamespace := input.Cluster.GetNamespace()
```

2025-02-04 13:26 UTC, jnummelin commented on e2e/workload_cluster_upgrade_test.go
> +		Flavor: "ooc",
I guess this maps to the yaml filename, right? Bit more descriptive names would make life easier 😄

2025-02-04 14:48 UTC, apedriza commented on .golangci.yml
> +    - ginkgolinter # Enforces standards of using ginkgo and gomega
mm I don't know why this diff appears, at the beginning I added some linter-ignoring stuff when ginkgo was added but then I removed it after agree on remove ginkgo. Anyway `ginkgolinter` was added some time ago probably for this usage: https://github.com/k0sproject/k0smotron/blob/main/internal/controller/k0smotron.io/suite_test.go 👈  I think is scaffolded code from kubebuilder. Doesn't add any value so I think could be removed

Done in 016c67a2c3271953cdaa7ba6d0d0327f202ce868

2025-02-04 14:48 UTC, apedriza commented on .github/workflows/go.yml
> +    name: E2E migration (WIP)
removed! 502a3701fdc83b2e67c61eac82ddc2ce3f32a67c

2025-02-04 15:02 UTC, apedriza commented on e2e/data/infrastructure-docker/cluster-template-ooc.yaml
is a cluster predefined configuration template that can be used by more than one test scenario (using docker infra provider). It is what CAPI refers as "flavor". Another custer-template for some of our tests should be a definition using clusterclass for example. In this case this cluster-template flavor uses is called "OOC" because controlplane is Out-of-Cluster (k0scontrolplane). I can rename this template to `cluster-template-k0scontrolplane` maybe.

2025-02-04 15:08 UTC, apedriza commented on e2e/workload_cluster_upgrade_test.go
> +		Flavor: "ooc",
wdyt about `out-of-cluster` meaning it uses k0scontrolplane in the cluster template? I could add some comments in the template header too.

2025-02-04 15:11 UTC, apedriza commented on e2e/util/controlplane.go
> +	// }, "10m")
done! 6e9350ce251da179469e0723d3193ee52a662069

2025-02-04 15:15 UTC, apedriza commented
@jnummelin thanks for the feedback! Comments addressed. Some of them accidentally lost but addressed too 9c9b3c0b201b7474177d1db4725c03f521d88bdc

2025-02-04 15:25 UTC, apedriza commented on e2e/data/infrastructure-docker/cluster-template-ooc.yaml
9c418b47a96a87da8ca576096faade88b560a324

2025-02-10 16:52 UTC, merged